-- 코드를 입력하세요
# SELECT BOOK_ID, AUTHOR_NAME, PUBLISHED_DATE FROM BOOK JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID WHERE BOOK.CATEGORY = "경제" ORDER BY BOOK.PUBLISHED_DATE ASC;

SELECT b.BOOK_ID,
       a.AUTHOR_NAME,
       DATE_FORMAT(b.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK b
JOIN AUTHOR a
  ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE b.CATEGORY = '경제'
ORDER BY b.PUBLISHED_DATE ASC;
